### PR TITLE
feat(): inject by tag

### PR DESCRIPTION
**Pull request by adibPlaybuzz**
I added the option to inject the svg defs by tag (e.g. body)

What do you think about it?

### CODE REVIEW

**Comment by danburzo** [comment]
Hi there! I like the idea of being able to use any CSS selector to insert the SVGs. 

Here's what I propose for this feature:

To avoid having multiple templates, we can replace `document.getElementById` with `document.querySelector`. With this pattern, you could say `container: '#svginjector'` or `container: 'body'`. This breaks compatibility with the current version, but that's okay and it's easy to update the Grunt script :-)

In addition, we'd need a new option called `mode` that can be one of `append` or `replace` (default being `replace`), which do the following:
* `append` will insert the SVG at the end of the container element (this is useful for using the `body`).
* `replace` will set the SVG as the content of the container element (via `innerHTML`).

(We could also do `prepend` if there's use case for that).

As for adding the SVG to the DOM, to avoid creating temporary elements, we can use [`insertAdjacentHTML`](https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentHTML) to insert the string directly.

**Comment by adibPlaybuzz** [comment]
sounds great!

**Comment by adibPlaybuzz** [comment]
I will do some cleanup and submit a new pr today... (-:

**Comment by danburzo** [comment]
Awesome! :+1:

**Comment by adibPlaybuzz** [comment]
Hi, 
What do you think about the update? (-:

**Comment by danburzo** [comment]
Excelent :-) 
(Sorry for the late reply)

**Pull request merged**
